- name: Change-RHEL-IP-Address
  hosts: all
  vars:
    conn_name: enp2s0
    old_ip_add: "192.168.1.165"
    new_ip_add: "192.168.1.169"
    old_gw4: "192.168.1.1"
    new_gw4: "192.168.1.1"

  tasks:
  - name: replace ip address
    replace:
      path: "/etc/sysconfig/network-scripts/ifcfg-{{ conn_name }}"
      regexp: "{{ old_ip_add }}"
      replace: "{{ new_ip_add }}"
      backup: no

  - name: replace gw address
    replace:
      path: "/etc/sysconfig/network-scripts/ifcfg-{{ conn_name }}"
      regexp: "{{ old_gw4 }}"
      replace: "{{ new_gw4 }}"
      backup: no
