- name: Change-RHEL-IP-Address
  hosts: vm-before
  connection: local
  gather_facts: yes
  vars:
    new_ip_add: "192.168.1.169/24"
    network_connections:

      # Create a bridge profile, which is the parent of VLAN.
      - name: enp2s0
        state: up
        type: ethernet
        interface_name: enp2s0
        ip:
          dhcp: no
          address:
            - "{{ new_ip_add }}"
          auto6: no
 tasks:
    -  Name: start the service
       service:
         name: NetworkManager
         state: started
         enabled: true
         
  roles:
    - redhat.rhel_system_roles.network
